const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish modern loft apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    },
    price: 1200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Mountain Retreat",
    description: "Enjoy peaceful mountain views from this beautiful countryside retreat.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    },
    price: 1800,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Luxury Villa with Pool",
    description: "Relax in this luxurious villa featuring a private swimming pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    },
    price: 3500,
    location: "Miami",
    country: "United States",
  },
  {
    title: "Cozy Cabin in the Woods",
    description: "A peaceful wooden cabin surrounded by beautiful forests and nature.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8",
    },
    price: 1100,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Seaside Apartment",
    description: "Wake up to stunning ocean views in this comfortable seaside apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    },
    price: 2200,
    location: "Santa Monica",
    country: "United States",
  },
  {
    title: "Elegant City Apartment",
    description: "A modern apartment located close to restaurants, shops, and attractions.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    },
    price: 1400,
    location: "Chicago",
    country: "United States",
  },
  {
    title: "Rustic Farmhouse",
    description: "Experience countryside living in this beautiful rustic farmhouse.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
    },
    price: 1700,
    location: "Nashville",
    country: "United States",
  },
  {
    title: "Ocean View Villa",
    description: "A stunning villa offering panoramic views of the ocean and coastline.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    },
    price: 4200,
    location: "Honolulu",
    country: "United States",
  },
  {
    title: "Minimalist Studio",
    description: "A clean and modern studio perfect for solo travelers and couples.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    },
    price: 900,
    location: "Boston",
    country: "United States",
  },
  {
    title: "Luxury Downtown Condo",
    description: "Enjoy premium amenities and city views from this luxury condominium.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154",
    },
    price: 2500,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Hidden Forest Cottage",
    description: "A quiet cottage hidden among tall trees and beautiful forest trails.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    },
    price: 1300,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Riverside Retreat",
    description: "Spend your vacation beside a peaceful river surrounded by nature.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    },
    price: 1600,
    location: "Bend",
    country: "United States",
  },
  {
    title: "Modern Beach House",
    description: "A stylish beach house with spacious rooms and incredible ocean views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1494526585095-c41746248156",
    },
    price: 3000,
    location: "San Diego",
    country: "United States",
  },
  {
    title: "Historic Townhouse",
    description: "Stay in a charming historic townhouse located in the city center.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    },
    price: 1900,
    location: "Boston",
    country: "United States",
  },
  {
    title: "Luxury Mountain Lodge",
    description: "Enjoy breathtaking mountain scenery from this luxurious mountain lodge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    },
    price: 2800,
    location: "Denver",
    country: "United States",
  },
  {
    title: "Coastal Escape",
    description: "Relax near the beach in this peaceful and comfortable coastal home.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    },
    price: 2100,
    location: "Charleston",
    country: "United States",
  },
  {
    title: "Urban Penthouse",
    description: "Experience luxury living in this spacious downtown penthouse.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
    },
    price: 5000,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Lakeside Cabin",
    description: "A cozy cabin with direct access to a beautiful peaceful lake.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    },
    price: 1450,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Charming Garden Home",
    description: "Stay in a beautiful home surrounded by colorful gardens.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    },
    price: 1550,
    location: "San Francisco",
    country: "United States",
  },
  {
    title: "Desert Villa",
    description: "A beautiful desert retreat with modern architecture and open spaces.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    },
    price: 2300,
    location: "Scottsdale",
    country: "United States",
  },
  {
    title: "Snowy Mountain Cabin",
    description: "Perfect winter getaway surrounded by snowy mountain landscapes.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09",
    },
    price: 2000,
    location: "Jackson Hole",
    country: "United States",
  },
  {
    title: "Luxury Lakeside Villa",
    description: "A spacious villa offering beautiful lake views and premium amenities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    },
    price: 3800,
    location: "Orlando",
    country: "United States",
  },
  {
    title: "Downtown Studio",
    description: "Affordable studio apartment located close to the city's main attractions.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1524758631624-e2822e304c36",
    },
    price: 850,
    location: "Seattle",
    country: "United States",
  },
  {
    title: "Private Island House",
    description: "Enjoy ultimate privacy in this stunning island vacation home.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    },
    price: 6000,
    location: "Key West",
    country: "United States",
  },
  {
    title: "Countryside Cottage",
    description: "A peaceful countryside cottage perfect for a relaxing weekend.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8",
    },
    price: 1250,
    location: "Austin",
    country: "United States",
  },
  {
    title: "Modern Glass House",
    description: "A stunning modern home featuring large windows and natural light.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    },
    price: 3200,
    location: "Palm Springs",
    country: "United States",
  },
  {
    title: "Beachside Bungalow",
    description: "A cozy bungalow just steps away from the sandy beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    },
    price: 1800,
    location: "Miami Beach",
    country: "United States",
  },
  {
    title: "Historic Villa",
    description: "Stay in a beautifully preserved villa filled with classic architecture.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    },
    price: 2400,
    location: "Savannah",
    country: "United States",
  },
  {
    title: "Forest View Apartment",
    description: "A peaceful apartment overlooking a lush green forest.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8",
    },
    price: 1350,
    location: "Asheville",
    country: "United States",
  },
  {
    title: "Luxury Ski Chalet",
    description: "Enjoy skiing and mountain adventures from this luxury chalet.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    },
    price: 3600,
    location: "Vail",
    country: "United States",
  },
  {
    title: "Tropical Paradise Villa",
    description: "A tropical villa surrounded by palm trees and beautiful beaches.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500534623283-312aade485b7",
    },
    price: 4100,
    location: "Maui",
    country: "United States",
  },
  {
    title: "City View Apartment",
    description: "Modern apartment with stunning views of the city skyline.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1515263487990-61b07816b324",
    },
    price: 1750,
    location: "Atlanta",
    country: "United States",
  },
  {
    title: "Peaceful River House",
    description: "Relax beside the river in this spacious and peaceful vacation home.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500534623283-312aade485b7",
    },
    price: 1650,
    location: "Boise",
    country: "United States",
  },
  {
    title: "Luxury Country Estate",
    description: "A large private estate surrounded by beautiful countryside.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    },
    price: 4500,
    location: "Dallas",
    country: "United States",
  },
  {
    title: "Cozy Downtown Home",
    description: "Comfortable home located within walking distance of downtown attractions.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    },
    price: 1450,
    location: "Philadelphia",
    country: "United States",
  },
  {
    title: "Sunset Beach House",
    description: "Watch beautiful sunsets from this comfortable beach house.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    },
    price: 2700,
    location: "Santa Barbara",
    country: "United States",
  },
  {
    title: "Modern Mountain Home",
    description: "A contemporary home with breathtaking mountain views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    },
    price: 2900,
    location: "Salt Lake City",
    country: "United States",
  },
  {
    title: "Chic Urban Loft",
    description: "Stylish loft apartment in one of the city's most vibrant neighborhoods.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    },
    price: 1550,
    location: "Brooklyn",
    country: "United States",
  },
  {
    title: "Lakefront Mansion",
    description: "Luxury mansion with private lake access and spacious living areas.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    },
    price: 5500,
    location: "Lake Placid",
    country: "United States",
  },
  {
    title: "Rustic Mountain Cabin",
    description: "Traditional wooden cabin perfect for nature lovers.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    },
    price: 1350,
    location: "Montana",
    country: "United States",
  },
  {
    title: "Elegant Beach Villa",
    description: "Elegant vacation villa with a private pool near the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154",
    },
    price: 3300,
    location: "Naples",
    country: "United States",
  },
  {
    title: "Cozy City Retreat",
    description: "A comfortable retreat in the middle of a busy city.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    },
    price: 1150,
    location: "Washington DC",
    country: "United States",
  },
  {
    title: "Forest Luxury Lodge",
    description: "Luxury lodge surrounded by tall trees and peaceful walking trails.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    },
    price: 2600,
    location: "Boulder",
    country: "United States",
  },
  {
    title: "Sunny Coastal Home",
    description: "Bright and comfortable home located near the beautiful coastline.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    },
    price: 1950,
    location: "Tampa",
    country: "United States",
  },
  {
    title: "Luxury City Penthouse",
    description: "Premium penthouse with panoramic skyline views and modern interiors.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
    },
    price: 4800,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Countryside Manor",
    description: "Spacious manor house surrounded by beautiful green landscapes.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    },
    price: 3700,
    location: "Charlottesville",
    country: "United States",
  },
  {
    title: "Modern Lakeside Home",
    description: "Modern home with large windows overlooking a peaceful lake.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    },
    price: 2450,
    location: "Madison",
    country: "United States",
  },
  {
    title: "Tropical Beach Cottage",
    description: "Small and cozy cottage perfect for a tropical vacation.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    },
    price: 1750,
    location: "Key Largo",
    country: "United States",
  },
  {
    title: "Downtown Luxury Suite",
    description: "A luxurious suite located in the center of the city.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1515263487990-61b07816b324",
    },
    price: 2100,
    location: "Houston",
    country: "United States",
  },
  {
    title: "Mountain View Cottage",
    description: "Charming cottage offering incredible views of the surrounding mountains.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09",
    },
    price: 1500,
    location: "Flagstaff",
    country: "United States",
  },
  {
    title: "Private Pool Retreat",
    description: "Relax in this private home featuring a beautiful swimming pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    },
    price: 2800,
    location: "Scottsdale",
    country: "United States",
  },
  {
    title: "Stylish Studio Apartment",
    description: "Compact and stylish apartment perfect for a short city stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    },
    price: 950,
    location: "Denver",
    country: "United States",
  },
  {
    title: "Beachfront Luxury Condo",
    description: "Modern condominium with direct access to a beautiful sandy beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    },
    price: 2900,
    location: "Fort Lauderdale",
    country: "United States",
  },
  {
    title: "Woodland Retreat",
    description: "A peaceful home surrounded by woods and fresh mountain air.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8",
    },
    price: 1200,
    location: "Olympic Peninsula",
    country: "United States",
  },
  {
    title: "Luxury Oceanfront Home",
    description: "Spacious luxury home overlooking the endless blue ocean.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    },
    price: 3900,
    location: "Newport Beach",
    country: "United States",
  },
  {
    title: "Historic Downtown Loft",
    description: "Beautiful loft combining historic architecture with modern comforts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    },
    price: 1600,
    location: "New Orleans",
    country: "United States",
  },
  {
    title: "Cozy Winter Chalet",
    description: "Warm and inviting chalet perfect for a winter holiday.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    },
    price: 2300,
    location: "Breckenridge",
    country: "United States",
  },
  {
    title: "Modern Desert House",
    description: "Contemporary desert home with stunning sunset views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154",
    },
    price: 2600,
    location: "Joshua Tree",
    country: "United States",
  },
  {
    title: "Garden Villa",
    description: "Beautiful villa surrounded by colorful gardens and greenery.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    },
    price: 2250,
    location: "San Jose",
    country: "United States",
  },
  {
    title: "Ocean Breeze Apartment",
    description: "Bright apartment with fresh ocean breezes and coastal views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    },
    price: 1850,
    location: "Virginia Beach",
    country: "United States",
  },
  {
    title: "Luxury Forest Villa",
    description: "Private luxury villa surrounded by peaceful forests.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    },
    price: 3400,
    location: "Lake Arrowhead",
    country: "United States",
  },
  {
    title: "Riverside Cabin",
    description: "Cozy cabin located directly beside a calm flowing river.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    },
    price: 1250,
    location: "Missoula",
    country: "United States",
  },
  {
    title: "Luxury Downtown Apartment",
    description: "Modern apartment close to restaurants, shopping, and nightlife.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    },
    price: 1800,
    location: "San Francisco",
    country: "United States",
  },
  {
    title: "Secluded Beach Cottage",
    description: "Enjoy complete peace and privacy in this charming beach cottage.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    },
    price: 2050,
    location: "Outer Banks",
    country: "United States",
  },
  {
    title: "Mountain Luxury Estate",
    description: "Large luxury estate with incredible panoramic mountain views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    },
    price: 5200,
    location: "Park City",
    country: "United States",
  },
  {
    title: "Urban Garden Apartment",
    description: "Modern city apartment featuring a private garden space.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    },
    price: 1650,
    location: "Washington DC",
    country: "United States",
  },
  {
    title: "Lakeside Luxury Cabin",
    description: "Beautiful cabin with private lake views and outdoor seating.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    },
    price: 2150,
    location: "Lake George",
    country: "United States",
  },
  {
    title: "Sunny Mountain Retreat",
    description: "Bright mountain retreat perfect for families and groups.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09",
    },
    price: 1900,
    location: "Santa Fe",
    country: "United States",
  },
  {
    title: "Elegant Coastal Villa",
    description: "Elegant villa located just minutes from the ocean.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    },
    price: 3100,
    location: "Monterey",
    country: "United States",
  },
  {
    title: "Cozy City Loft",
    description: "Stylish loft with an open floor plan in the city center.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    },
    price: 1350,
    location: "Detroit",
    country: "United States",
  },
  {
    title: "Private Mountain Cabin",
    description: "Private cabin surrounded by beautiful mountains and trees.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    },
    price: 1550,
    location: "Big Bear",
    country: "United States",
  },
  {
    title: "Luxury Pool House",
    description: "Modern vacation house featuring a large private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    },
    price: 3600,
    location: "Las Vegas",
    country: "United States",
  },
  {
    title: "Charming Village Home",
    description: "Peaceful home located in a quiet and charming village.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    },
    price: 1150,
    location: "Burlington",
    country: "United States",
  },
  {
    title: "Modern Waterfront Villa",
    description: "Contemporary villa overlooking beautiful waterfront scenery.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154",
    },
    price: 4300,
    location: "Seattle",
    country: "United States",
  },
  {
    title: "Coastal Family Home",
    description: "Spacious family-friendly home located close to the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    },
    price: 2200,
    location: "Jacksonville",
    country: "United States",
  },
  {
    title: "Forest Edge Cottage",
    description: "Charming cottage sitting at the edge of a peaceful forest.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8",
    },
    price: 1400,
    location: "Eugene",
    country: "United States",
  },
];

module.exports = { data: sampleListings };