module.exports = {
    countries: [
        "India",
        "United States",
        "United Kingdom",
        "Australia",
        "Canada",
        "United Arab Emirates",
    ],
    states: [
        "Odisha",
        "Maharashtra",
        "Goa",
        "Himachal Pradesh",
        "Rajasthan",
        "Kerala",
        "Karnataka",
        "Delhi",
        "California",
        "New York",
        "Dubai",
    ],
    cities: [
        "Bhubaneswar",
        "Mumbai",
        "Goa",
        "Manali",
        "Jaipur",
        "Kochi",
        "Bengaluru",
        "New Delhi",
        "New York City",
        "Dubai",
        "Sydney",
        "Toronto",
    ],
};
